### ISSUE TITLE
(bug) Python Provider Stops Working with OpenFeature Python SDK v0.5.0

### ISSUE THREAD

**Issue by ChihweiLHBird** [thomaspoignant/go-feature-flag#1644]
### Observed behaviour

`FAILED tests/test_gofeatureflag_python_provider.py::test_should_return_an_error_if_no_targeting_key - AssertionError: 'No exception expected get_client() got an unexpected keyword argument 'name'`

### Expected Behavior

Tests should run without any exception reported.

### Steps to reproduce

```bash
cd openfeature/providers/python-provider
pip install -e ".[dev]"
pytest ./tests/
```
